### ISSUE TITLE
Allow tcp channel to be used even if tcp channel is not available when radioroom service starts

### ISSUE THREAD

**Issue by StephBMG** [envirover/SPLRadioRoom#72]
Currently tcp channel is never used if tcp channel failed when radioroom service starts.

This means that even if tcp channel is available after the service startup, il will never be used.

This would be very useful for UAV where there is no cellular connection when the UAV is powered up.

**Comment by davidalois** [comment]
I have the same issue

**Comment by envirover** [comment]
@StephBMG @davidalois Please try radioroom build #318 from  https://github.com/envirover/SPLRadioRoom/releases/tag/untagged-43d2280cf98c192bd03b

That build has a fix for issue #72 that initializes TCP channel before sending reports if the channel was not initialized on startup.
